name: Markdown Lint
on: [pull_request]
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          config: 'markdownlint.jsonc'
          globs: '**/*.md'
